version: "3"

# in staging and production don't need --reload, we can remove volume
services:
  web:
    build: .
    command: sh -c "uvicorn main:app --port=8000 --host=0.0.0.0"
    env_file:
      - .env.staging
    ports:
      - 8000:8000
